### ISSUE TITLE
PCB thickness

### ISSUE THREAD

**Issue by 7407chrisl** [KunaiGC/KunaiGC#10]
Hi, 

What PCB thickness do you recommend when ordering the QSB and main board?

Thanks

**Comment by TharathielCB** [comment]
QSB: 1,2 mm
KunaiGC: 0,8 mm

**Comment by TharathielCB** [comment]
added in wiki:
https://github.com/KunaiGC/KunaiGC/wiki/Build-the-KunaiGC#recommend-pcb-thickness
