### ISSUE TITLE
Different BOM

### ISSUE THREAD

**Issue by gnaghi** [KunaiGC/KunaiGC#13]
On the wiki page (https://github.com/KunaiGC/KunaiGC/wiki/Build-the-KunaiGC), 2 types of resistor are needed : 1 x 10k ohm, and 3 x 220 ohm, but, on the schematic, there are 1x 10k ohm, 1 x 100 ohm, and 2 x 470 ohm.

I guess the good values are the one on the schematic ?

**Comment by TharathielCB** [comment]
wiki updated
