### ISSUE TITLE
start.dol file doesn't override onboard swiss

### ISSUE THREAD

**Issue by axmccx** [KunaiGC/KunaiGC#15]
I've placed the latest version of Swiss on my SD2SP2, on the root of the SD card named `start.dol`, however when I hold start at bootup, it still boots the older onboard version of Swiss. Anything I should be doing differently? 

Alternatively, is there any way to update the on board Swiss? It kinda defeat the benefit of this mod if it can't be updated.

**Comment by TharathielCB** [comment]
To update the internal swiss please follow the [KunaiUpdater guide](https://github.com/KunaiGC/KunaiGC/wiki/Update-the-KunaiGC)
You will found the dol in the release
