### ISSUE TITLE
What is the pinouts for the kunaigc to ipl chip???

### ISSUE THREAD

**Issue by zin0099** [KunaiGC/KunaiGC#16]
I have lost my qsb and decided to wire the kunai to the ipl with 30.  Gauge wire...but that 7th pad that isn't marked on the test page with no color isn't marked....where do the wires go...no diagram and the only 3 videos of the install don't talk about it

**Comment by ManCloud** [comment]
There is a mapping in the Installation section in the wiki
https://github.com/KunaiGC/KunaiGC/wiki/Installation
the pad you're most likely referring to (can only guess without a picture) is only for stability reasons and not connected to the KunaiGC at all 👍
