### ISSUE TITLE
Resistor values

### ISSUE THREAD

**Issue by 7407chrisl** [KunaiGC/KunaiGC#7]
Hi, I was little confused on the recommended resistor values.  In the PCB schematic it says R1 is 100ohm and R3 and R4 is 470ohm.  In the wiki section it says to use 220ohm for all three.  Then the boards being sold by consoles4you are using 22ohm for R1 and 220ohm for R3 and R4.  Thanks!

**Comment by ManCloud** [comment]
Yeah it's a little inconsistent as it really doesn't matter that much.
We'll fix that and enter same values everywhere.

All combinations work just fine as Re and R4 are current limiting resistors for the LEDs and R1 ist just a safety resistor that could even be shorted.

**Comment by TharathielCB** [comment]
wiki updated
