### ISSUE TITLE
Question - Able to boot into Swiss by default, IE reverse the start button on boot

### ISSUE THREAD

**Issue by 0mni** [KunaiGC/KunaiGC#8]
See subject, want to be able to boot into Swiss on powering on the gamecube by default. Didn't see an option that jumped out to me that would do that, does one exists and if not, can it be added in future?

**Comment by ManCloud** [comment]
Will be added in the future 👌

**Comment by 0mni** [comment]
> Will be added in the future 👌

Awesome!
