### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by raguila3** [KunaiGC/KunaiGC#9]
I’ve installed the KunaiGC chip, had run a game through Swiss and everything. I was playing with the settings but changing them back and then suddenly I don’t have video output anymore. I got scared that I might have shorted my KunaiGC chip as I did not cover the pins in the back. I opened my GC and I noticed that the KunaiGC chip doesn’t blink the LED lights like it did at the initial boot. I desoldered it to check the pins in the back and attached is a picture of them. If the pins look fine, is it normal for the board to not blink the LED lights anymore? I want to make sure my problem is not the chip and hopefully just my HDMI converter not being strong enough.

![image](https://github.com/KunaiGC/KunaiGC/assets/56001601/4356c8bb-c085-4137-a5bf-d034f5d31dda)

**Comment by TharathielCB** [comment]
Hi,

if you need support with the installation please join the new retro discord. https://discord.gg/TYRYdXsBxr
To get access to the Nintendo section you need to select the designated role.
